---
title: "R Notebook"
output: html_notebook
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(maps)
library(tmap)
library(sp)
library(sf)
```

```{r}
#install and cleaning data
#data=read.csv("C:/Users/Lenovo/AppData/Local/Temp/baiduyunguanjia/onlinedit/cache/defb3b5a8a2002b9a8ce4b75e18ae5f2/PublicAssistanceFundedProjectsDetails.csv")
#hurricane=filter(data,incidentType=="Hurricane")
#hurricane$year=substr(hurricane$declarationDate,1,4)
#hurricane=filter(hurricane,year=="2009"|year=="2010"|year=="2011"|year=="2012"|year=="2013"|year=="2014"|year=="2016"|year=="2015"|year=="2017"|year=="2018")
#hurricane=hurricane%>%filter(projectAmount>=0&totalObligated>=0)


#Then we use this hurricane dataset after this

```

```{r}

#group the data 
#county = map_data("county")
#county_state = hurricane %>% group_by(state, county) %>% summarise(
  #total_project = sum(projectAmount),
  #total_Federal = sum(federalShareObligated),
  #toatl_total = sum(totalObligated)
)

#join the latitude ande longtitude into the data
#county_state$subregion = tolower(county_state$county[])
#county_state$region = tolower(county_state$state[])
#total_map = right_join(county_state,
 #                      county,
  #                     by = c('subregion' = 'subregion', 'region' = 'region'))
#write.csv(total_map,"C:/Users/Lenovo/Documents/615mid-project/maps.csv")
#Then we use this hurricane dataset after this
```
```{r}
total_map=read.csv("https://raw.githubusercontent.com/lzt666666/615midterm_project/main/maps.csv")
summary(total_map)
total_map$project_legend=total_map$total_project%>%cut(breaks=c(1.356e+03,1.781e+05,1.012e+06,5.603e+06,9.801e+09),include.lowest = T)

total_map$toatl_total_legend=total_map$toatl_total%>%cut(breaks=c(1.017e+03,1.379e+05 ,7.684e+05,4.375e+06,8.809e+09))

ggplot()+
  geom_polygon(data=county,aes(long,lat,group=group),color="black",fill="white")+
  geom_polygon(data=total_map,aes(long,lat,group=group,fill=project_legend))+
  geom_path(county, mapping=aes(x=long, y=lat, group=group),color="grey")+
  scale_fill_brewer(palette="Blues")+
  ggtitle("total project amount by county")+
  theme(plot.title=element_text(hjust=0.5))


ggplot()+
  geom_polygon(data=county,aes(long,lat,group=group),color="blue",fill="white")+
  geom_polygon(data=total_map,aes(long,lat,group=group,fill=toatl_total_legend))+
  geom_path(county, mapping=aes(x=long, y=lat, group=group),color="grey")+
  ggtitle("Total Obligated amount by county")+
  scale_fill_brewer(palette="Reds")+
  theme(plot.title=element_text(hjust=0.5))
```

